Update do README.MD
fga-eps-mds/2022-1-TiControla-FrontEnd pull request #55
Opened 2022-08-12 16:41 UTC by OrlandiRodrigo

Mudanças com base em outros repositórios para tornar o projeto mais acessível.
Membros do PR incluem os que estão trabalhando na documentação.

2022-08-12 16:42 UTC, OrlandiRodrigo commented
Acham as mudanças boas? Qualquer coisa podem falar

2022-08-18 14:27 UTC, roddas approved these changes

2022-08-19 13:24 UTC, mateus-de-siqueira commented on README.md
> +Estes repositórios são dedicados para o desenvolvimento e contibuição do softare **TiControla**. O repositório principal é o FrontEnd, parente dos repositórios BackEnd e Docs. As issues estão sendo l
Tá escrito 'Softare' - Correto Software

2022-08-19 13:27 UTC, mateus-de-siqueira commented on README.md
> +Essa aplicação tem seu ambiente configurado através de conteiners Docker, portanto, tem como pré-requisitos a instalação do Docker e Docker-compose. Também é necessário ter o Git instalado para clona
Reforlumar a questão do Docker

2022-08-19 13:30 UTC, mateus-de-siqueira requested changes
Rever questões adicionadas nos comentários

2022-08-24 18:28 UTC, leommiranda commented
É necessário mudar o nome da branch para seguir os [padrões de nomeação](https://github.com/fga-eps-mds/2022-1-TiControla-Docs/blob/main/CONTRIBUTING.md#121-nomear-branches-remotas). O seu nickname do github não deve estar na branch. Minha sugestão seria mudar de "OrlandiRodrigo-README" para "readme". Além disso, como as palavras já são divididas por meio do caracter "-", não é uma boa prática usar letras maiúsculas.

2022-09-05 22:28 UTC, OrlandiRodrigo commented on README.md
> +Essa aplicação tem seu ambiente configurado através de conteiners Docker, portanto, tem como pré-requisitos a instalação do Docker e Docker-compose. Também é necessário ter o Git instalado para clona
Como reformular a questão do docker? Expandir a explicação? Corrigir as condições necessárias?

2022-09-15 10:27 UTC, merged